# Generated by Django 4.2.7 on 2026-03-16 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=500, unique=True, verbose_name="Token"),
                ),
                (
                    "jti",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="JWT ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Fecha de Expiración"),
                ),
                (
                    "revoked",
                    models.BooleanField(default=False, verbose_name="Revocado"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revocación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Refresco",
                "verbose_name_plural": "Tokens de Refresco",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked"],
                        name="authenticat_user_id_0749d9_idx",
                    ),
                    models.Index(fields=["token"], name="authenticat_token_c19e1a_idx"),
                    models.Index(fields=["jti"], name="authenticat_jti_ab2b92_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Stored separately in case user is deleted",
                        max_length=150,
                        verbose_name="Nombre de Usuario",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Ver"),
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("login", "Iniciar Sesión"),
                            ("logout", "Cerrar Sesión"),
                            ("failed_login", "Intento de Inicio de Sesión Fallido"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="E.g., Patient, Appointment, ClinicalRecord",
                        max_length=100,
                        verbose_name="Tipo de Recurso",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID del Recurso",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Detalles"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="authenticat_user_id_3b88ca_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="authenticat_action_4a725a_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="authenticat_resourc_b40bc0_idx",
                    ),
                ],
            },
        ),
    ]
