# Generated by Django 4.2.7 on 2026-03-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Recordatorio de Cita"),
                            ("appointment_confirmation", "Confirmación de Cita"),
                            ("payment_reminder", "Recordatorio de Pago"),
                            ("treatment_update", "Actualización de Tratamiento"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "Correo Electrónico"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Método de Envío",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Asunto"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email del Destinatario",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="Teléfono del Destinatario",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("delivered", "Entregado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Programado para"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado el"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos de Respuesta"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="appointments.appointment",
                        verbose_name="Cita",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="notificatio_patient_4c3e97_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_d8d933_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "status"],
                        name="notificatio_notific_a659f1_idx",
                    ),
                ],
            },
        ),
    ]
