# Generated by Django 4.2.7 on 2026-03-16 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("informed_consent", "Consentimiento Informado"),
                            ("treatment_plan", "Plan de Tratamiento"),
                            ("privacy_policy", "Política de Privacidad"),
                            ("financial_agreement", "Acuerdo Financiero"),
                            ("anesthesia_consent", "Consentimiento para Anestesia"),
                            ("x_ray_consent", "Consentimiento para Radiografías"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Acuerdo",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido del Acuerdo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("signed", "Firmado"),
                            ("declined", "Rechazado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded signature image",
                        null=True,
                        verbose_name="Datos de Firma Digital",
                    ),
                ),
                (
                    "signed_by_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Firmado por (nombre)",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Firma"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP de Firma"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Expiración"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="agreements/pdfs/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agreements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acuerdo",
                "verbose_name_plural": "Acuerdos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="agreements__patient_f72520_idx",
                    ),
                    models.Index(
                        fields=["agreement_type", "status"],
                        name="agreements__agreeme_ac0e09_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="agreements__created_08898c_idx"
                    ),
                ],
            },
        ),
    ]
