# Generated by Django 4.2.7 on 2026-03-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("installments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Tarjeta de Crédito/Débito"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID de Transacción"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Respuesta del Gateway"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado el"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email del Cliente",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre del Cliente",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "installment_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="installments.installmentpayment",
                        verbose_name="Pago de Cuota",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_payments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago en Línea",
                "verbose_name_plural": "Pagos en Línea",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Stripe Charge ID",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Marca de Tarjeta",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Últimos 4 dígitos",
                    ),
                ),
                (
                    "card_exp_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mes de Expiración"
                    ),
                ),
                (
                    "card_exp_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Año de Expiración"
                    ),
                ),
                (
                    "stripe_metadata",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadata de Stripe"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "online_payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_details",
                        to="online_payments.onlinepayment",
                        verbose_name="Pago en Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Stripe",
                "verbose_name_plural": "Pagos Stripe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="onlinepayment",
            index=models.Index(
                fields=["patient", "status"], name="online_paym_patient_e01de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinepayment",
            index=models.Index(
                fields=["transaction_id"], name="online_paym_transac_9bcdd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinepayment",
            index=models.Index(
                fields=["status", "payment_date"], name="online_paym_status_a44df3_idx"
            ),
        ),
    ]
