# Generated by Django 4.2.7 on 2026-03-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto Total"
                    ),
                ),
                (
                    "number_of_installments",
                    models.PositiveIntegerField(verbose_name="Número de Cuotas"),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto por Cuota"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("delinquent", "Moroso"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installment_plans",
                        to="budgets.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Cuotas",
                "verbose_name_plural": "Planes de Cuotas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Número de Cuota"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Efectivo"),
                            ("card", "Tarjeta"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "installment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="installments.installmentplan",
                        verbose_name="Plan de Cuotas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Cuota",
                "verbose_name_plural": "Pagos de Cuotas",
                "ordering": ["installment_number"],
            },
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(
                fields=["patient", "status"], name="installment_patient_f1b4eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(
                fields=["status", "start_date"], name="installment_status_bbefd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installmentpayment",
            index=models.Index(
                fields=["installment_plan", "status"],
                name="installment_install_4863a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentpayment",
            index=models.Index(
                fields=["due_date", "status"], name="installment_due_dat_e307cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="installmentpayment",
            unique_together={("installment_plan", "installment_number")},
        ),
    ]
